return {
    guid = "{e7409390-d4c4-4315-9768-72df1b3702e6}",
    template = "small-item",

    id = "paper",
    name = "a blank sheet of paper",
    keywords = {"paper", "sheet", "page", "blank paper", "sheet of paper", "parchment", "stationery"},
    description = "A single sheet of cream-coloured paper, slightly foxed at the edges but otherwise blank. It has the dry, clean smell of a stationer's shop -- a rare thing in a room that smells of tallow and old wool.",

    on_feel = "Thin, flat, smooth. The edges are slightly foxed. Paper -- unmistakable even in the dark.",
    on_smell = "Faintly fibrous. The dry, clean smell of a stationer's shop.",

    size = 1,
    weight = 0.1,
    categories = {"small", "writable", "flammable"},
    portable = true,
    material = "paper",

    -- The paper is a writable surface. Writing requires a writing_instrument tool.
    -- When written on, the engine performs a DYNAMIC MUTATION: it generates a new
    -- object definition at write-time with the player's words baked into the
    -- description and written_text field. This is NOT a pre-built variant file --
    -- the mutation is generated by the engine using the player's exact input.
    writable = true,
    written_text = nil,

    location = nil,

    on_look = function(self)
        if self.written_text then
            return "A sheet of paper with writing on it. It reads:\n\n  \"" .. self.written_text .. "\""
        end
        return self.description
    end,

    mutations = {
        write = {
            -- DYNAMIC MUTATION: engine generates the new object definition at runtime.
            -- The player's words are captured and baked into the mutated object's code.
            -- Pattern: WRITE <words> ON paper WITH <writing_instrument>
            requires_tool = "writing_instrument",
            dynamic = true,
            mutator = "write_on_surface",
            message = "You write carefully on the paper. The words appear in steady strokes.",
            fail_message = "You have nothing to write with.",
        },
        burn = {
            becomes = nil,
            requires_tool = "fire_source",
            message = "The paper catches instantly, curling and blackening. The words -- if there were any -- are gone forever.",
            fail_message = "You have nothing to set it alight with.",
        },
    },
}
