return {
    guid = "{94d05bd1-8393-4a54-a21f-7eae6ed503d9}",
    id = "meat",
    name = "meat",
    density = 1050,
    melting_point = nil,
    ignition_point = 300,
    hardness = 1,
    flexibility = 0.8,
    absorbency = 0.6,
    opacity = 1.0,
    flammability = 0.2,
    conductivity = 0.1,
    fragility = 0.7,
    value = 3,
    description = "Raw animal flesh.",
    on_feel = "Wet and yielding.",
    on_smell = "Iron and blood.",
}
